Description:  This template deploys a RDS instance

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: cloudguruchallenge-june-2021
  
  DBName:
    Description: Please enter the Database name
    Type: String
    Default: challenge

  DBUsername:
    Description: Please enter the Database Username
    Type: String
    Default: challenge
    
  DBClass:
    Description: Please enter the Instance Class
    Type: String
    Default: db.t2.micro
    
  DBAllocatedStorage:
    Description: Please enter the storage of the DB
    Type: String
    Default: 20  
  
  DBPassword:
    NoEcho : true
    Description: Please enter the Instance Class
    Type: String
    Default: ACGChall3ng3

Resources:
  DBSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: description
      SubnetIds: 
        !Split
          - ","
          - Fn::ImportValue: !Sub ${EnvironmentName}:IsolatedSubnets
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName:
        Ref: DBName
      Engine: postgres
      MasterUsername:
        Ref: DBUsername
      DBInstanceClass:
        Ref: DBClass
      DBSecurityGroups:
      - Ref: DBSecurityGroup
      AllocatedStorage:
        Ref: DBAllocatedStorage
      MasterUserPassword:
        Ref: DBPassword
      DBSubnetGroupName: 
        Ref: DBSubnetGroup
  DBSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      EC2VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}:VPC
      DBSecurityGroupIngress: 
        - 
          EC2SecurityGroupId: 
            Ref: "WebServerSecurityGroup"
      GroupDescription: Frontend Access
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 and SSH access
      VpcId: 
        Fn::ImportValue: !Sub ${EnvironmentName}:VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
        
Outputs:
  WebServerSecurityGroup:
    Description: Web Server Security Group
    Value: !Ref WebServerSecurityGroup
    Export: 
      Name: !Sub ${EnvironmentName}:WebServerSecurityGroup
  DBHostName:
    Description: Database hostname
    Value: !GetAtt DBInstance.Endpoint.Address
    Export: 
      Name: !Sub ${EnvironmentName}:DBHostName
  DBUsername:
    Description: Database username
    Value: !Ref DBUsername
    Export: 
      Name: !Sub ${EnvironmentName}:DBUsername
  DBPassword:
    Description: Database password
    Value: !Ref DBPassword
    Export: 
      Name: !Sub ${EnvironmentName}:DBPassword